######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 27 18:14:28 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
# Input
HEADERS += player.h renderarea.h window.h
SOURCES += main.cpp player.cpp renderarea.cpp window.cpp
