# #####################################################################
# Automatically generated by qmake (2.01a) Tue Oct 27 21:08:29 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../server
CONFIG += debug
QT += network opengl

# Input
HEADERS += connection.h \
    engine.h \
    game.h \
    object.h \
    renderarea.h \
    window.h \
	player.h \
	particle.h \
<<<<<<< HEAD:client/client.pro
    stats.h
=======
	setupdialog.h
>>>>>>> 1930c314b962e375b5b8fd122da5a890890feabe:client/client.pro
SOURCES += connection.cpp \
    engine.cpp \
    game.cpp \
    main.cpp \
    object.cpp \
    renderarea.cpp \
    window.cpp \
	setupdialog.cpp

