######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 27 20:39:24 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += area.h player.h server.h unit.h utils.h bullet.h bot.h
SOURCES += area.cpp main.cpp player.cpp server.cpp unit.cpp bullet.cpp bot.cpp
